apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:k/JtTkA04APQU8kgI/ZEb5fjH6ejT9xVsgSelhvQd+DptEQC6fhuddAiVWDS2Nq+TboHn/4JkXS1lAbyxVydMBfQ+NObJNMBJ3FxFoig8lcL5DzZJbKOcx0+WnJ4xAmSp35HMXrrqB6bqzgJ/0LijdsnT/vR6oUwiK/zBKffQdNIncx63f+xqW/LXwNwzDSfIImG+NQdgOUKJvcYP3uA7X7rwhtSDUDeaMdrPKT8sCRN25dMrq82qh1SABDKIngS6PCp0Qjw0zMWTC/HqGtjJpJ9RihG4cdU64rLQMBzsAjplVAwuD1DRZZGTP4=,iv:CY4GMxzCgAKBr+thDdZ2OKwElJO/p/lhDXOckwkRv5o=,tag:lBfBjtk2lo+V6S6h9cGiRw==,type:str]
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeS9yR0VmWkQ1SEduMHJj
            eUxiaEJQczIvOWw0THBnNGpUY3A4S2ZkQlN3CjdxckNrMXBVU2x2R1hLR05mbUdo
            T09ZQmk5OUZsaWdNVHRQbmpBQjR0RUkKLS0tIDJmUFJOckEzSllmZ0lZRE5mcmNu
            UW9UTkpuZUtLU3BlRlNYbGRoUGptMEUKcb3kq/vSbRwS+bC+fKFvtBXYbniHFHya
            EBzJVsjMaCPDKmCcYyCG189CHq3eNozgJH2cQ6CS/uAvziqCZoOATQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T19:39:07Z"
    mac: ENC[AES256_GCM,data:YI2kH4jDJDsAfNjszOqTj6i98y2Ee95fz5NipLAMTj7JLuUx8kpozpgLnQhoETdm56uZ/kW2P029Gh+3lmrpYE0mIBCs9lUIX3y99+y/p+ncSdRFZZvKlmeWbPznPVA+RqYax5nLq+/lmpmQS9Ii8lEh7sX9JJRWzb6AswIVsFI=,iv:U0OhXnFYZfOU+J+XlBC55DksxflXGSTVS3UAnOOi7t8=,tag:pNptUzQyTphTVYl0Y7ixXQ==,type:str]
    encrypted_regex: ^(data|stringData|adminPassword)$
    version: 3.11.0
