apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:QEz7QlEJa2I1O7SXfp58UdwJJqs1BHdOp4AzQD9Cqgta6OQyhmBzUAe6f90y85G/S1RLG4cmQ2RmSsSpCVGgZxX7hxR0aoyDIAefffvnI5LuELu1lV0zYEbcv1dAhIIauDrI2xDvoCMH5t6P6IcvbMHZb5Y6aOsxEeMBNbbz8pqcoIuXwQkOL0aRxQK0WX7qe2zBG483Izsx9mt6MDmr1TsL5d9paXIIw76+rED1wvbCefPcMJCEcRMpJCJWLNIEJbLfuqQ147Qu9U3wRKg65uL98acyP95yr+MDIkezdK5lVgAmuCGEX4YEJic=,iv:oS3zYbqdD7iSGh+JvhDVfm0uR8+NaURateMB2YWONlI=,tag:h7SG56PHMWvLZtKeuyv6Lg==,type:str]
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUXNva3g2TDFhRzladnU3
            NEZXa0R4VXZIdUNYKzVETjd3RlRhVHA3WDB3CnNzbDJlZEVyTk5nenU1bUttKzB2
            c2pBc0g0SFdwWjY0VDdTNnd6RUpxdVkKLS0tIFdVbUhSVjBkWTZpVUxwbWlqQ0RG
            R1gwdWxFZXZHZE44dVRBK0w4b0ZNRFkKFlcO4IDQyqJAhilGVTVQsKJaH+/vxHiG
            +5onJ7IYcE2mJcqLBJYvN4KJJYqkW7MkPLC5IcZHrSp28PtTu8uVog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T13:49:11Z"
    mac: ENC[AES256_GCM,data:Rg+M5V2/71qXS9m7oUF9OfDdFbgTw4BtdpD7MKusz0CBm4Kyda3TAKyysCcV/nZZQgVEtw/2/qqN5VP9yLqYtRh5WUE5iZeDMWWodM3tPLnOPZgjk9qS7wTab60+Zvsseg6ObT6uG4zyIHaCMlixLIkrpgl/GiKOo3oVopQK3ko=,iv:ucJ7aeyuD+0rARWzNecgxPqj374/eIbNNJOWHJB5Qzw=,tag:lRRJqdO7GAF/Hdm2irO8wA==,type:str]
    encrypted_regex: ^(data|stringData|adminPassword)$
    version: 3.11.0
