apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:cJWrSydanpxAD8V356vtVYTaTJIqfYbsOTdEaO7ZDoYIg3zQWnoBwoyaoGCC0sJ//XXdedQ=,iv:wDgAIsmWGjei2yZX5cKgvAIzox0DYJgSpg+Rre98na8=,tag:NaA3uEzOQq9BJi+vWSsYFQ==,type:str]
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdmNQaXhmRWNDWXJzTW52
            VG9XUWZmb0p1SEd2VTlKMTRUemlOZkQ5alZVCktKUS91VTkxR3dUSzRmRmFzSnJV
            alFVa1pidDdDVkczeXFWZUNYc3JhbWsKLS0tIDVKbVdCbVlKamhJeDFkY2pDbTlZ
            S2lxMW0wNVFaRklkU2FKYnVSN1RqZWMKFciiCcqBnYzNaCFOPyfDKcAW4xipk9/q
            roPgfxA2cYEH2qryQrW7diF5FOg+yt8M5nMq6me4pwFLTvYroBxk6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T22:35:07Z"
    mac: ENC[AES256_GCM,data:zDfggjAQactMJq1wZUYFqqOVJWfAkGIi4DCTFJ1fE8L7z6H9e07es1rFYrkUTBKrio41t22g36yTxDbfBpCvLNvvKSE3rXNioZVnMEpGmridLiPNaVbb8CuUbcL7IjizsXmefZksTY8FUAc/CjpiCvww8jJAXXb0KIWKiZPKRlY=,iv:aAw9OwRew3K4lUaG4HnJkJbZe5O5knUQJpSEJ4lIgLA=,tag:/gr2dAG1yskhcSzT/IEprQ==,type:str]
    encrypted_regex: ^(data|stringData|adminPassword)$
    version: 3.11.0
