apiVersion: v1
data:
  tunnel-credentials.json: eyJBY2NvdW50VGFnIjoiYTdkMzU5YWNlNTY5MjhiNzhkZTYxMmFhMDgxZjI0ZTMiLCJUdW5uZWxTZWNyZXQiOiJicnJoTkpadnNJcTdQTkRrc1RNNWlhcnFYcXJCVENlQVViRzQvaTh2bXpzPSIsIlR1bm5lbElEIjoKIjI3YWM3ZDA3LTY3OGYtNGQ1Mi05OTE0LWE5MzYyY2NlNTk1ZSIsIkVuZHBvaW50IjoiIn0K
kind: Secret
metadata:
  name: tunnel-credentials
