apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:ik+RmgqHvT2Rt45XWu5vtvRRSz9TGft6riV4Syai34JeAH6Jv9uwJ8OT14W6kkDQH+V4CupS8QhlVjwaSfphL/xPMdMGVBYacOCiidME/FBM28Q6l1rBGdMuWLXZIcyR+C60sCH6cqqrRdoVf4gjPMtUKrhSw02pl0CtWulWZjc6jbBDRg1LOS2XgrIrSqehO64SvnFPpZT0OVu0k0/JEPtOEk5VvPDXWe8M7evseddvZFdQHa2LF0KMt2kLXfNcU2VrqU7cxfUZf6Ms7Dge+WeaJsLCY+xli6SZFVnrXvsBDAJArg030fXuB+s=,iv:T3j7xbyqWHVFOuD7ued0xvSHsy49DNuNyEc0CJGHgrI=,tag:fhPakxIWJjhqBs5ZK0J/TA==,type:str]
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SkZVQnhrN3pMUHN1UFBB
            Z0t0K1ppclJrb1ZlOXFaQjljKzVjTTI0NHlzCkNCVzk5SFVFU0JuNzRUcXBUYnB1
            QzE4YWJkYk1CNE9BWHlyVi9MNk4vckkKLS0tIEtwWHIzaC9BSWNIUWlYN3FjOUEz
            VDJkSTJrZ1k4L3dBZ3VRMjJuTGhtV2sK+b7wOxZKRI3i21FMk8wEPtjnSFr8Lv+J
            MnWShDCEI9dlNoRdN3ZnzCw1WkZYpl1k9sOQ3FAik+24PvTudeVurQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T13:01:21Z"
    mac: ENC[AES256_GCM,data:3FkqHnvouzf4QFkENvf50ZdUhfMBoRuMQqNTDvY9O3h5MhWUKZSN6AZ6Cw3j/gvaV0aGVWtTxPm9/yp3J3Rr+MmCsxVndekvhVwZfWeaHP3B0e5S0HwCL7j+zpDmn4VFoy1PzesoR01Tns6aLkZQggYAxzNXD/u0V9kT5gs3qNc=,iv:b+WpjRG2E8WdLf+7THJREWlD34WMfyO01zRCPYWkGFM=,tag:lOBboHfQUNCjlZ0JA00FZw==,type:str]
    encrypted_regex: ^(data|stringData|adminPassword)$
    version: 3.11.0
