apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ReMpLP0IPJZQK/wNFwWoFQ==,iv:T35oiuPu1MWTtLFNInZE1qMUN3kiRqtpjzKopZoGOiw=,tag:p7yB6T1OKWoDbndPb6/PDg==,type:str]
    user: ENC[AES256_GCM,data:o84uC0+LKRU=,iv:h7asvwQJyEcfqfmX3RmX2SJaZe6lvqzg362BaFqgsl4=,tag:fqrRSOmeuT+Nf8SJ3tweWQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcitmMkNiRFM1UVFyejFw
            S3pmUGdEVG9RNTRGQ3Q2YTdOU0VVTE4rSUU0CjNEcjR1ei9LUmg1cis0aGFTRWZT
            NWR6K3hKbit1YWpZOFNTVVdWTHJyancKLS0tIDArc3NOSW54bE5OZDRsQmFhV0dL
            eE9XcU1ZVmpXZGNFV0VBaU1vaXhtdEEKsMFxxtoGYgV+A8ys/TSjc6pFW0TvMbEP
            hqt/wMC1ibPxG//V8GB0kaMFq7DyARkEh34abm9MRClCAHcczE3dXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T20:25:47Z"
    mac: ENC[AES256_GCM,data:XFhgrqkTjrGT2E3xwCQYmLvYa3VCN2pKzrQXf8IpGc0sFSdIeWdP6HDDQfzJWRJkOCQGbBO5e33jmNrj6iOOikhbTQivUkFv9oaa8Z7lb64rTsQdcNOOfhxf0R8G+JzYmGXrX9iaCjAXiFSlXlRFMMGXrpWYjoBYhh3fmWtKwxQ=,iv:5VZq2YwrFMYotQkd2EEGZ/BTrgGAhJIWD+1bTiBLsj4=,tag:0iKNcy/CrBBAcYie6BwJug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
