apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:jfgIwneoc7E=,iv:pqPexPe5MdZ9GL5eQGOND5sPPZ/OfFk0dgmIunmV7Hs=,tag:9t+IGO93YST6ZmhhOqfdjQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:BcQIOl90xFH+qce8bKjsug==,iv:vnVrN+NSPONsy7hNFpxqriGD1lv4Rz6p/44OyVgrLm4=,tag:qkP7LUGUXmLe8JeSegCRJQ==,type:str]
kind: Secret
metadata:
    name: linkding-secrets
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZjJ1bVdjUUNFWkJQWnlI
            YlpuOVRJcmtaR0hoWlRMbHUvZGl4VWZ4VEFvCk4rU1BzdGdSaDZFOUNPK216d3Iy
            NFphQXc0enY1dEJIMnp0SUNYalpnVUEKLS0tIFdzVWxCekVyeTZMb1Z1cHdZQXQy
            YlF3RUt6V0hpWWQ3ZGFIM3dLRFAyemsKOXitQyXdxVRz9YTM+fJpMC+XSkP1SeTn
            Eh/aHEIDpK2dRvjl77x3PFwkW4UoDrOziBw8aEZvCUXa4Vg0LYoOaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T13:42:40Z"
    mac: ENC[AES256_GCM,data:YfpcD13hwDCKAg+5UnJoyN9wCtsSbgFCNTTBWnonyKhxvQkdFoi8PSqz6JIAW6QowgcCHQOvzdhLVypj+n2VUCqYQlpCxjj9u2bEYoEb6AXUIiXa1e9hxb+fLbR3Bw+EtYbrk0ZAt3LA/WJwLi7e0cUEv/XRpfLtHfJOB231CPQ=,iv:Z7/7N83J+KdBAMWCAMaxtLczAEnbsXXCPSMxw4FwK8c=,tag:+qgr8MzDP9a/EaCh84NaVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
