apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 66.2.2
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
                namespace: monitoring
            interval: 12h
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    driftDetection:
        mode: enabled
        ignore:
            # Ignore "validated" annotation which is not inserted during install
            - paths:
                - /metadata/annotations/prometheus-operator-validated
              target:
                kind: PrometheusRule
    values:
        grafana:
            adminPassword: ENC[AES256_GCM,data:k4dgV4x4G5/Ugg==,iv:m1ga/wAeNpGU9pp1zGbsK5FGR1rx3LrmG4+MEAueKlk=,tag:VPSugEs2qCbFWGMpJu1RwA==,type:str]
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.shirlenelim.se
                path: /
                pathType: Prefix
sops:
    age:
        - recipient: age1kk0pr2s3cmmy7lmp90hptz46vr6vdr3dq8t6a5cnhtvtkz90speqsyvysn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bk1RN055M0pJOHNaVlJh
            Q0pNSG9NSXUyenhqRUl6YVMvWTdFOFBCdUU4CnFTcWJCcGx6MzJCZTBKRmdMbFFT
            S0NVa1VkOWUzZFNUdWF6TkpFVWovRVEKLS0tIDJyUGdCOXVYWWMwWGYrTjhTc3ZC
            dE9rYW1MUHJ0VUMxR25BZFdoMUJZUTQKO1o5r28OozLzcOAjn7HfYf16l6+uGPpp
            9HOJxirJnCC0xpeLPpo/COh7Z3iUckcTy+DZLOH/r8EQsMoIVhZu6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T14:00:32Z"
    mac: ENC[AES256_GCM,data:WD2gfwJhCR6ZUr13s2M+lLhdheyIVFRtqsgkYuGzr+QS1Kv5qh8whZSc2DwHWzL9MHYJwQ5TXdkePupEZJH0MKiK/MkokqjA1KAnJkmjDDCmOngEojjn/q7VbqpEuejMgPgdCXpBHL2ER71CzbtKV1U1upFZVEn0hzlWZartVw8=,iv:IG30UUUrZdv/zSV7MA+BQdoHzK7wlJNMZff/oXy09w4=,tag:El2TwS7BwFZ4VGhW3/QfFg==,type:str]
    encrypted_regex: ^(data|stringData|adminPassword)$
    version: 3.11.0
