apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels: 
      app: linkding
  template:
    metadata:
      labels: 
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports: 
            - containerPort: 9090
          volumeMounts:       
            - name: linkding-data
              mountPath: /data  # where Linkding stores its data 
      securityContext:
        runAsNonRoot: true
        fsGroup: 0 #all mounted volumes owner
        runAsUser: 33
        runAsGroup: 33
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data