apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels: 
      app: linkding
  template:
    metadata:
      labels: 
        app: linkding
      # This annotation is used by the Linkding application to determine the base URL for generating links.
      # It should be set to the external URL where Linkding will be accessible.
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics" # Optional, if it is not /metrics
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports: 
            - containerPort: 9090
          envFrom:
            - secretRef:
               name: linkding-secrets
          volumeMounts:       
            - name: linkding-data
              mountPath: /etc/linkding/data  # where Linkding stores its data
      securityContext:
        runAsNonRoot: true
        fsGroup: 0 #all mounted volumes owner
        runAsUser: 33
        runAsGroup: 33
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data